### ISSUE TITLE
Navbar and Footer logo isn't clickable

### ISSUE THREAD

**Issue by stefanoskapa** [stefanoskapa/SudokuBase#18]
It is commong practice to make the logo a link that redirects to the home page

**Comment by doboianh** [comment]
I want to do it. Can you guide me ?

**Comment by NguyenLyy** [comment]
I want to do it. Can you guide me?????

**Comment by stefanoskapa** [comment]
Thanks for your interest! This issue has already been resolved, but you can pick another one. Have a look at the Issues tab and 
 let me know if you have any questions
