### ISSUE TITLE
Usernames with spaces are allowed

### ISSUE THREAD

**Issue by stefanoskapa** [stefanoskapa/SudokuBase#5]
It is good practice not to allow spaces in usernames

**Comment by namangirdhar16** [comment]
hey @stefanoskapa i would like to work on this, also is this project accepted in hacktoberfest?

**Comment by fuscati** [comment]
Hey! Can I work on this? I like your project a lot. Thank you!

**Comment by stefanoskapa** [comment]
Welcome @namangirdhar16 har16 and @fuscati ! Unfortunately, this project doesn't participate in Hacktoberfest. But let me know if I can be of any help regarding the project structure, the current issue or any other question you might have. You can start right away by making your own fork and then cloning the project into your computer. After you commit your changes, push on your fork and make a pull request. Also, I will soon provide some instructions in case you want to test-run the project locally.

**Comment by stefanoskapa** [comment]
@fuscati be aware that in java regex you have to use double backslash, as single backslash is an escape character for String as well
