### ISSUE TITLE
Github link on footer

### ISSUE THREAD

**Issue by stefanoskapa** [stefanoskapa/SudokuBase#9]
At the moment there is no github link on sudokubase.com. A suggestion would be a small clickable github logo on the footer (carefull, footer is responsive)

**Comment by DerekJxy** [comment]
Hi, there! Would you mind if I give it a shot?

**Comment by stefanoskapa** [comment]
Not at all, go ahead!

**Comment by stefanoskapa** [comment]
Thanks, good job!
